#!/bin/sh

# what to open with? $EDITOR, but vi if unset or NULL
open=${EDITOR:-vi}

# open the actual file
if [ 0 -eq $# ]; then
	$open "$HOME/Todo/TODO.txt"
elif [ 1 -eq $# ]; then
	$open "$HOME/Todo/TODO-${1}.txt"
else
	echo "Usage: todo [subject]"
	exit 1
fi
