#!/bin/sh

# Check we are not running as root
if [ "$EUID" -eq 0 ]; then
	echo "Error: This script shouldn't be run as root!"
	echo "It will elevate permissions when needed."
	exit 1
fi

echo "Updating all packages..."

# Check for -y or --yes parameter
PACMAN_YES=""
DEFAULT_YES=""
case $1 in
	-y)
		PACMAN_YES="--noconfirm"
		DEFAULT_YES="-y"
		;;
	--yes)
		PACMAN_YES="--noconfirm"
		DEFAULT_YES="-y"
		;;
esac

# AUR managers and pacman as a fallback
if command -v paru > /dev/null; then
	echo -e "\nUpdating system packages and AUR"
	echo "$ paru -Syu $PACMAN_YES"
	paru -Syu $PACMAN_YES
elif command -v yay > /dev/null; then
	echo -e "\nUpdating system packages and AUR"
	echo "$ yay -Syu $PACMAN_YES"
	yay -Syu $PACMAN_YES
elif command -v pacman > /dev/null; then
	echo -e "\nUpdating system packages"
	echo "$ sudo pacman -Syu $PACMAN_YES"
	sudo pacman -Syu $PACMAN_YES
fi

# apt
if command -v apt-get > /dev/null; then
	echo -e "\nUpdating system packages"
	echo "$ sudo apt-get update $DEFAULT_YES"
	sudo apt-get update $DEFAULT_YES
	echo "$ sudo apt-get upgrade $DEFAULT_YES"
	sudo apt-get upgrade $DEFAULT_YES
fi

# dnf
if command -v dnf > /dev/null; then
	echo -e "\nUpgrading system packages"
	echo "$ sudo dnf update $DEFAULT_YES"
	sudo dnf update $DEFAULT_YES
fi

# flatpak
if command -v flatpak > /dev/null; then
	echo -e "\nUpdating Flatpak packages..."
	echo "$ flatpak update $DEFAULT_YES"
	flatpak update $DEFAULT_YES
fi
